[package]
name = "multihash"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[features]
default = []
validation = ["lazy_static"]
validation_sha2 = ["sodiumoxide"]

[dependencies]
lazy_static = { version = "*", optional = true }
sodiumoxide = { version = "*", optional = true }
