[package]
name = "multihash"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[features]
default = []
validation = []
generation = []
sha2 = ["sodiumoxide"]

[dependencies]
sodiumoxide = { version = "*", optional = true }
